[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugins/denite_add.rc.vim'
hook_source = 'source ~/.config/nvim/plugins/denite_source.rc.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
source ~/.config/nvim/plugins/deol.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = 'source ~/.config/nvim/plugins/defx_add.rc.vim'
hook_source = 'source ~/.config/nvim/plugins/defx_source.rc.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rwd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:go_fmt_command = "goimports"
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
'''

