name: macos

on: [push]

jobs:
    macos-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run link
              run: make link

            - name: Run brew
              run: make brew

            - name: Run nodenv
              run: make nodenv

            - name: Run rbenv
              run: make rbenv

            - name: Run pyenv
              run: make pyenv

            - name: Run nvim
              run: make nvim

            - name: Run chsh
              run: make chsh
 
            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"
