name: macos

on: [push]

jobs:
    macos-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run brew
              run: brew install fish nodenv rbenv pyenv

            - name: Run fish
              run: fish

            - name: Run chsh
              run: make chsh

            - name: Run link
              run: make link

            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"

            - name: Run nodenv
              run: make nodenv

            - name: Run rbenv
              run: make rbenv

            - name: Run pyenv
              run: make pyenv
 
            - name: Run source
              run: source ./.config/fish/config.fish
