name: macos

on: [push]

jobs:
    macos-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run brew
              run: brew install fish nodenv rbenv pyenv

            - name: Run fish
              run: fish

            - name: Run chsh
              run: make chsh

            - name: Run link
              run: fish -c make link

            - name: Check link
              run: fish -c ls -la $HOME/.config | grep -- "->"

            - name: Run nodenv
              run: fish -c make nodenv

            - name: Run rbenv
              run: fish -c make rbenv

            - name: Run pyenv
              run: fish -c make pyenv
 
            - name: Run source
              run: fish -c source ./.config/fish/config.fish
