name: macos

on: [push]

jobs:
    macos-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run link
              run: make link

            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"

            - name: Run brew
              run: make brew

            - name: Run nodenv
              run: make nodenv

            - name: Cache rbenv
              uses: actions/cache@v2
              id: cache_rbenv
              with:
                  path: /home/runner/.rbenv
                  key: ${{ runner.os }}-rbenv-${{ hashFiles('**/.ruby-version') }}
                  restore-keys: |
                      {{ runner.os }}-rbenv-

            - name: Run rbenv
              run: make rbenv

            - name: Run pyenv
              run: make pyenv

            - name: Run nvim
              run: make nvim

            - name: Restart shell
              run: exec $SHELL -l

            - name: Run fish
              run: make fish

            - name: Run chsh
              run: make chsh
