name: macos

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macos-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run link
              run: make link

            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"

            - name: Run brew
              run: make brew

            - name: Run chsh
              run: make chsh

            - name: Run fish
              run: fish

            - name: Run nodenv
              run: make nodenv

            - name: Run rbenv
              run: make rbenv

            - name: Run pyenv
              run: make pyenv
