name: macos

on: [push]

jobs:
    macos-required-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run link
              run: make link

            - name: Run required brew
              run: make required-brew

            - name: Run nodenv
              run: make nodenv

            - name: Run pyenv
              run: make pyenv

            - name: Run nvim
              run: source ~/.bashrc && source ~/.bash_profile && make nvim

            - name: Run rbenv
              run: make rbenv

            - name: Run fish
              run: make fish

            - name: Run chsh
              run: make chsh

            - name: Run reload
              run: make reload

            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"

            - name: Check fish
              run: ls ./.config/fish

            - name: Check fish variable
              run: cat ./.config/fish/fish_variables

            - name: Check node
              run: fish -c "node -v"

            - name: Check ruby
              run: fish -c "ruby -v"

            - name: Check python
              run: fish -c "python --version"

    macos-all-test:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Run all
              run: make all

            - name: Check link
              run: ls -la $HOME/.config | grep -- "->"

            - name: Check fish
              run: ls ./.config/fish

            - name: Check fish variable
              run: cat ./.config/fish/fish_variables

            - name: Check node
              run: fish -c "node -v"

            - name: Check ruby
              run: fish -c "ruby -v"

            - name: Check python
              run: fish -c "python --version"

