name: macos

on:
	push:
		branches: [ master ]
	pull_request:
		branches: [ master ]

jobs:
	macos-test:
		runs-on: macos-latest

		steps:
			- uses: actions/checkout@v2

			- name: Run brew bundle
			  run: brew bundle

			- name: Run fisher
			  run: fisher

